### ISSUE TITLE
Move this repo into https://github.com/apache/incubator-pagespeed-ngx

### ISSUE THREAD

**Issue by oschaaf** [We-Amp/ngx-pagespeed-alpine#11]
@nberlee wdyt? Is it time? :) Would you care to help out with moving the contents of this repo?

**Comment by nberlee** [comment]
Yes it's time, and I have some spare time, so just say when :)

**Comment by oschaaf** [comment]
Well, anytime you are up for it. If you have a planned approach, maybe you can create a PR to https://github.com/apache/incubator-pagespeed-ngx ? I'll be happy to facilitate the reviewing/merging on the other side to land it. What do you think, should we just move this repo into a subdirectory in ngx_pagespeed's codebase?

**Comment by nberlee** [comment]
My Yubikey broke, just before my vacation started (when I would have time for this). So it took a bit longer.
I created a Pull request, which you can change as a maintainer ( this way is just a proposal, I am not insulted in any way if you totally change it). However, all files needed in a DockerHub build either need to be in the same of child directory. As we now have 4 flavors on DockerHub, everything needs to be there 4 times... :(
See: https://github.com/apache/incubator-pagespeed-ngx/pull/1598
