### ISSUE TITLE
Update the image

### ISSUE THREAD

**Issue by extremeshok** [We-Amp/ngx-pagespeed-alpine#15]
Hi

is it possible to release an update image based on the new nginx ?

**Comment by oschaaf** [comment]
This repo has moved over to https://github.com/apache/incubator-pagespeed-ngx/tree/master/docker
I'm sure there's a newer nginx version offered there, though recently some efforts have stalled because of some of the deps being complex to upgrade. ymmv

**Comment by extremeshok** [comment]
I developed my own docker nginx mainline with pagespeed : https://cloud.docker.com/repository/docker/extremeshok/nginx
